export interface NPIRecord {
  // Core identifiers
  "NPI": string;
  "Entity Type Code": string;
  "Replacement NPI": string;
  "Employer Identification Number (EIN)": string;

  // Provider name (individual)
  "Provider Last Name (Legal Name)": string;
  "Provider First Name": string;
  "Provider Middle Name": string;
  "Provider Name Prefix Text": string;
  "Provider Name Suffix Text": string;
  "Provider Credential Text": string;

  // Provider name (organization)
  "Provider Organization Name (Legal Business Name)": string;
  "Provider Other Organization Name": string;
  "Provider Other Organization Name Type Code": string;

  // Other names
  "Provider Other Last Name": string;
  "Provider Other First Name": string;
  "Provider Other Middle Name": string;
  "Provider Other Name Prefix Text": string;
  "Provider Other Name Suffix Text": string;
  "Provider Other Credential Text": string;
  "Provider Other Last Name Type Code": string;

  // Mailing address
  "Provider First Line Business Mailing Address": string;
  "Provider Second Line Business Mailing Address": string;
  "Provider Business Mailing Address City Name": string;
  "Provider Business Mailing Address State Name": string;
  "Provider Business Mailing Address Postal Code": string;
  "Provider Business Mailing Address Country Code (If outside U.S.)": string;
  "Provider Business Mailing Address Telephone Number": string;
  "Provider Business Mailing Address Fax Number": string;

  // Practice location address
  "Provider First Line Business Practice Location Address": string;
  "Provider Second Line Business Practice Location Address": string;
  "Provider Business Practice Location Address City Name": string;
  "Provider Business Practice Location Address State Name": string;
  "Provider Business Practice Location Address Postal Code": string;
  "Provider Business Practice Location Address Country Code (If outside U.S.)": string;
  "Provider Business Practice Location Address Telephone Number": string;
  "Provider Business Practice Location Address Fax Number": string;

  // Dates & status
  "Provider Enumeration Date": string;
  "Last Update Date": string;
  "NPI Deactivation Reason Code": string;
  "NPI Deactivation Date": string;
  "NPI Reactivation Date": string;
  "Provider Sex Code": string;
  "Certification Date": string;

  // Authorized official
  "Authorized Official Last Name": string;
  "Authorized Official First Name": string;
  "Authorized Official Middle Name": string;
  "Authorized Official Title or Position": string;
  "Authorized Official Telephone Number": string;
  "Authorized Official Name Prefix Text": string;
  "Authorized Official Name Suffix Text": string;
  "Authorized Official Credential Text": string;

  // Taxonomies 1–15
  "Healthcare Provider Taxonomy Code_1": string;
  "Provider License Number_1": string;
  "Provider License Number State Code_1": string;
  "Healthcare Provider Primary Taxonomy Switch_1": string;
  "Healthcare Provider Taxonomy Group_1": string;
  "Healthcare Provider Taxonomy Code_2": string;
  "Provider License Number_2": string;
  "Provider License Number State Code_2": string;
  "Healthcare Provider Primary Taxonomy Switch_2": string;
  "Healthcare Provider Taxonomy Group_2": string;
  "Healthcare Provider Taxonomy Code_3": string;
  "Provider License Number_3": string;
  "Provider License Number State Code_3": string;
  "Healthcare Provider Primary Taxonomy Switch_3": string;
  "Healthcare Provider Taxonomy Group_3": string;
  "Healthcare Provider Taxonomy Code_4": string;
  "Provider License Number_4": string;
  "Provider License Number State Code_4": string;
  "Healthcare Provider Primary Taxonomy Switch_4": string;
  "Healthcare Provider Taxonomy Group_4": string;
  "Healthcare Provider Taxonomy Code_5": string;
  "Provider License Number_5": string;
  "Provider License Number State Code_5": string;
  "Healthcare Provider Primary Taxonomy Switch_5": string;
  "Healthcare Provider Taxonomy Group_5": string;
  "Healthcare Provider Taxonomy Code_6": string;
  "Provider License Number_6": string;
  "Provider License Number State Code_6": string;
  "Healthcare Provider Primary Taxonomy Switch_6": string;
  "Healthcare Provider Taxonomy Group_6": string;
  "Healthcare Provider Taxonomy Code_7": string;
  "Provider License Number_7": string;
  "Provider License Number State Code_7": string;
  "Healthcare Provider Primary Taxonomy Switch_7": string;
  "Healthcare Provider Taxonomy Group_7": string;
  "Healthcare Provider Taxonomy Code_8": string;
  "Provider License Number_8": string;
  "Provider License Number State Code_8": string;
  "Healthcare Provider Primary Taxonomy Switch_8": string;
  "Healthcare Provider Taxonomy Group_8": string;
  "Healthcare Provider Taxonomy Code_9": string;
  "Provider License Number_9": string;
  "Provider License Number State Code_9": string;
  "Healthcare Provider Primary Taxonomy Switch_9": string;
  "Healthcare Provider Taxonomy Group_9": string;
  "Healthcare Provider Taxonomy Code_10": string;
  "Provider License Number_10": string;
  "Provider License Number State Code_10": string;
  "Healthcare Provider Primary Taxonomy Switch_10": string;
  "Healthcare Provider Taxonomy Group_10": string;
  "Healthcare Provider Taxonomy Code_11": string;
  "Provider License Number_11": string;
  "Provider License Number State Code_11": string;
  "Healthcare Provider Primary Taxonomy Switch_11": string;
  "Healthcare Provider Taxonomy Group_11": string;
  "Healthcare Provider Taxonomy Code_12": string;
  "Provider License Number_12": string;
  "Provider License Number State Code_12": string;
  "Healthcare Provider Primary Taxonomy Switch_12": string;
  "Healthcare Provider Taxonomy Group_12": string;
  "Healthcare Provider Taxonomy Code_13": string;
  "Provider License Number_13": string;
  "Provider License Number State Code_13": string;
  "Healthcare Provider Primary Taxonomy Switch_13": string;
  "Healthcare Provider Taxonomy Group_13": string;
  "Healthcare Provider Taxonomy Code_14": string;
  "Provider License Number_14": string;
  "Provider License Number State Code_14": string;
  "Healthcare Provider Primary Taxonomy Switch_14": string;
  "Healthcare Provider Taxonomy Group_14": string;
  "Healthcare Provider Taxonomy Code_15": string;
  "Provider License Number_15": string;
  "Provider License Number State Code_15": string;
  "Healthcare Provider Primary Taxonomy Switch_15": string;
  "Healthcare Provider Taxonomy Group_15": string;

  // Other identifiers 1–50
  "Other Provider Identifier_1": string;
  "Other Provider Identifier Type Code_1": string;
  "Other Provider Identifier State_1": string;
  "Other Provider Identifier Issuer_1": string;
  "Other Provider Identifier_2": string;
  "Other Provider Identifier Type Code_2": string;
  "Other Provider Identifier State_2": string;
  "Other Provider Identifier Issuer_2": string;
  "Other Provider Identifier_3": string;
  "Other Provider Identifier Type Code_3": string;
  "Other Provider Identifier State_3": string;
  "Other Provider Identifier Issuer_3": string;
  "Other Provider Identifier_4": string;
  "Other Provider Identifier Type Code_4": string;
  "Other Provider Identifier State_4": string;
  "Other Provider Identifier Issuer_4": string;
  "Other Provider Identifier_5": string;
  "Other Provider Identifier Type Code_5": string;
  "Other Provider Identifier State_5": string;
  "Other Provider Identifier Issuer_5": string;
  "Other Provider Identifier_6": string;
  "Other Provider Identifier Type Code_6": string;
  "Other Provider Identifier State_6": string;
  "Other Provider Identifier Issuer_6": string;
  "Other Provider Identifier_7": string;
  "Other Provider Identifier Type Code_7": string;
  "Other Provider Identifier State_7": string;
  "Other Provider Identifier Issuer_7": string;
  "Other Provider Identifier_8": string;
  "Other Provider Identifier Type Code_8": string;
  "Other Provider Identifier State_8": string;
  "Other Provider Identifier Issuer_8": string;
  "Other Provider Identifier_9": string;
  "Other Provider Identifier Type Code_9": string;
  "Other Provider Identifier State_9": string;
  "Other Provider Identifier Issuer_9": string;
  "Other Provider Identifier_10": string;
  "Other Provider Identifier Type Code_10": string;
  "Other Provider Identifier State_10": string;
  "Other Provider Identifier Issuer_10": string;
  "Other Provider Identifier_11": string;
  "Other Provider Identifier Type Code_11": string;
  "Other Provider Identifier State_11": string;
  "Other Provider Identifier Issuer_11": string;
  "Other Provider Identifier_12": string;
  "Other Provider Identifier Type Code_12": string;
  "Other Provider Identifier State_12": string;
  "Other Provider Identifier Issuer_12": string;
  "Other Provider Identifier_13": string;
  "Other Provider Identifier Type Code_13": string;
  "Other Provider Identifier State_13": string;
  "Other Provider Identifier Issuer_13": string;
  "Other Provider Identifier_14": string;
  "Other Provider Identifier Type Code_14": string;
  "Other Provider Identifier State_14": string;
  "Other Provider Identifier Issuer_14": string;
  "Other Provider Identifier_15": string;
  "Other Provider Identifier Type Code_15": string;
  "Other Provider Identifier State_15": string;
  "Other Provider Identifier Issuer_15": string;
  "Other Provider Identifier_16": string;
  "Other Provider Identifier Type Code_16": string;
  "Other Provider Identifier State_16": string;
  "Other Provider Identifier Issuer_16": string;
  "Other Provider Identifier_17": string;
  "Other Provider Identifier Type Code_17": string;
  "Other Provider Identifier State_17": string;
  "Other Provider Identifier Issuer_17": string;
  "Other Provider Identifier_18": string;
  "Other Provider Identifier Type Code_18": string;
  "Other Provider Identifier State_18": string;
  "Other Provider Identifier Issuer_18": string;
  "Other Provider Identifier_19": string;
  "Other Provider Identifier Type Code_19": string;
  "Other Provider Identifier State_19": string;
  "Other Provider Identifier Issuer_19": string;
  "Other Provider Identifier_20": string;
  "Other Provider Identifier Type Code_20": string;
  "Other Provider Identifier State_20": string;
  "Other Provider Identifier Issuer_20": string;
  "Other Provider Identifier_21": string;
  "Other Provider Identifier Type Code_21": string;
  "Other Provider Identifier State_21": string;
  "Other Provider Identifier Issuer_21": string;
  "Other Provider Identifier_22": string;
  "Other Provider Identifier Type Code_22": string;
  "Other Provider Identifier State_22": string;
  "Other Provider Identifier Issuer_22": string;
  "Other Provider Identifier_23": string;
  "Other Provider Identifier Type Code_23": string;
  "Other Provider Identifier State_23": string;
  "Other Provider Identifier Issuer_23": string;
  "Other Provider Identifier_24": string;
  "Other Provider Identifier Type Code_24": string;
  "Other Provider Identifier State_24": string;
  "Other Provider Identifier Issuer_24": string;
  "Other Provider Identifier_25": string;
  "Other Provider Identifier Type Code_25": string;
  "Other Provider Identifier State_25": string;
  "Other Provider Identifier Issuer_25": string;
  "Other Provider Identifier_26": string;
  "Other Provider Identifier Type Code_26": string;
  "Other Provider Identifier State_26": string;
  "Other Provider Identifier Issuer_26": string;
  "Other Provider Identifier_27": string;
  "Other Provider Identifier Type Code_27": string;
  "Other Provider Identifier State_27": string;
  "Other Provider Identifier Issuer_27": string;
  "Other Provider Identifier_28": string;
  "Other Provider Identifier Type Code_28": string;
  "Other Provider Identifier State_28": string;
  "Other Provider Identifier Issuer_28": string;
  "Other Provider Identifier_29": string;
  "Other Provider Identifier Type Code_29": string;
  "Other Provider Identifier State_29": string;
  "Other Provider Identifier Issuer_29": string;
  "Other Provider Identifier_30": string;
  "Other Provider Identifier Type Code_30": string;
  "Other Provider Identifier State_30": string;
  "Other Provider Identifier Issuer_30": string;
  "Other Provider Identifier_31": string;
  "Other Provider Identifier Type Code_31": string;
  "Other Provider Identifier State_31": string;
  "Other Provider Identifier Issuer_31": string;
  "Other Provider Identifier_32": string;
  "Other Provider Identifier Type Code_32": string;
  "Other Provider Identifier State_32": string;
  "Other Provider Identifier Issuer_32": string;
  "Other Provider Identifier_33": string;
  "Other Provider Identifier Type Code_33": string;
  "Other Provider Identifier State_33": string;
  "Other Provider Identifier Issuer_33": string;
  "Other Provider Identifier_34": string;
  "Other Provider Identifier Type Code_34": string;
  "Other Provider Identifier State_34": string;
  "Other Provider Identifier Issuer_34": string;
  "Other Provider Identifier_35": string;
  "Other Provider Identifier Type Code_35": string;
  "Other Provider Identifier State_35": string;
  "Other Provider Identifier Issuer_35": string;
  "Other Provider Identifier_36": string;
  "Other Provider Identifier Type Code_36": string;
  "Other Provider Identifier State_36": string;
  "Other Provider Identifier Issuer_36": string;
  "Other Provider Identifier_37": string;
  "Other Provider Identifier Type Code_37": string;
  "Other Provider Identifier State_37": string;
  "Other Provider Identifier Issuer_37": string;
  "Other Provider Identifier_38": string;
  "Other Provider Identifier Type Code_38": string;
  "Other Provider Identifier State_38": string;
  "Other Provider Identifier Issuer_38": string;
  "Other Provider Identifier_39": string;
  "Other Provider Identifier Type Code_39": string;
  "Other Provider Identifier State_39": string;
  "Other Provider Identifier Issuer_39": string;
  "Other Provider Identifier_40": string;
  "Other Provider Identifier Type Code_40": string;
  "Other Provider Identifier State_40": string;
  "Other Provider Identifier Issuer_40": string;
  "Other Provider Identifier_41": string;
  "Other Provider Identifier Type Code_41": string;
  "Other Provider Identifier State_41": string;
  "Other Provider Identifier Issuer_41": string;
  "Other Provider Identifier_42": string;
  "Other Provider Identifier Type Code_42": string;
  "Other Provider Identifier State_42": string;
  "Other Provider Identifier Issuer_42": string;
  "Other Provider Identifier_43": string;
  "Other Provider Identifier Type Code_43": string;
  "Other Provider Identifier State_43": string;
  "Other Provider Identifier Issuer_43": string;
  "Other Provider Identifier_44": string;
  "Other Provider Identifier Type Code_44": string;
  "Other Provider Identifier State_44": string;
  "Other Provider Identifier Issuer_44": string;
  "Other Provider Identifier_45": string;
  "Other Provider Identifier Type Code_45": string;
  "Other Provider Identifier State_45": string;
  "Other Provider Identifier Issuer_45": string;
  "Other Provider Identifier_46": string;
  "Other Provider Identifier Type Code_46": string;
  "Other Provider Identifier State_46": string;
  "Other Provider Identifier Issuer_46": string;
  "Other Provider Identifier_47": string;
  "Other Provider Identifier Type Code_47": string;
  "Other Provider Identifier State_47": string;
  "Other Provider Identifier Issuer_47": string;
  "Other Provider Identifier_48": string;
  "Other Provider Identifier Type Code_48": string;
  "Other Provider Identifier State_48": string;
  "Other Provider Identifier Issuer_48": string;
  "Other Provider Identifier_49": string;
  "Other Provider Identifier Type Code_49": string;
  "Other Provider Identifier State_49": string;
  "Other Provider Identifier Issuer_49": string;
  "Other Provider Identifier_50": string;
  "Other Provider Identifier Type Code_50": string;
  "Other Provider Identifier State_50": string;
  "Other Provider Identifier Issuer_50": string;

  // Organization flags
  "Is Sole Proprietor": string;
  "Is Organization Subpart": string;
  "Parent Organization LBN": string;
  "Parent Organization TIN": string;
}
